name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

env:
  APP_NAME: apiok-admin
  GO_VERSION: '1.23'
  NODE_VERSION: '18'

jobs:
  build:
    uses: asita88/ci-templates/.github/workflows/build-release-go.yml@main
    permissions:
      contents: write
    with:
      app_name: ${{ env.APP_NAME }}
      go_version: ${{ env.GO_VERSION }}
      node_version: ${{ env.NODE_VERSION }}
      build_script: scripts/build.sh
    secrets: inherit
